# Generated by Django 2.2.7 on 2019-12-10 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phenopackets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenopacket',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phenopackets', to='chord.Dataset'),
        ),
    ]
